# Generated by Django 4.0.4 on 2022-05-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotegory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
    ]
