# Generated by Django 4.0.4 on 2022-05-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cotegory_options_alter_prices_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='cat',
        ),
    ]
