# Generated by Django 4.0.4 on 2022-05-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_prices_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='cat',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='main.cotegory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prices',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prices',
            name='title',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
