# Generated by Django 4.0.4 on 2022-05-18 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_prices_cat_prices_price_prices_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cotegory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Услуги'),
        ),
    ]
